version: '3'

services:
  app:
    container_name: url_checker_app
    build: ./
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    command: bash -c 'while ! nc -z db 5432; do sleep 1; done; python manage.py migrate --noinput; python manage.py runserver ${DB_HOST}:${DB_PORT}'
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    env_file:
      - .env
  
  db:
    container_name: url_checker_postgres
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always